CREATE TABLE hometohome3_addresses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    number TEXT NOT NULL,
    street TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip TEXT NOT NULL,
    name TEXT,
    email TEXT,
    gospelpresentation TEXT,
    newsalvations INTEGER,
    notes TEXT
);